<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$layoutSetting = $this->themeSetting('browse_layout');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (!isset($layoutSetting) || strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
?>



<div class="browse-control-mobile">
<button type="button" class="browse-toggle closed">Tools</button>
</div>
<div class="browse-controls closed">
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>        
    </div>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php
foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]')]) : $itemSet->displayTitle();
    $body = $bodyTerm ? $itemSet->value($bodyTerm) : $itemSet->displayDescription();
?>
    <div class="medium-3 cell">
    <?php if ($thumbnail = $this->thumbnail($itemSet, 'square')): ?>
        <?php echo $itemSet->linkRaw($thumbnail, null, ['class' => 'thumbnail']); ?>
    <?php endif; ?>
    </div>
    
        
    <div class="resource-meta medium-7 cell">
            <h2><?php echo $itemSet->link($heading); ?></h2>
            <?php if ($body): ?>
            <p><?php echo $body; ?></p>
            <?php endif; ?>
    </div>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
