<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
?>

<div class="resource-title medium-12 cell">
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>
  
<div class="media-embed medium-9 cell">
<?php if ($embedMedia && $itemMedia): ?>

<?php foreach ($itemMedia as $media):
    echo $media->render();
endforeach;
?>
<?php echo $item->displayValues(); ?>

</div>


<?php endif; ?>


<div class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?> medium-3 cell">
    <?php $this->trigger('view.show.before'); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <dl>
    <?php if (count($itemSets) > 0): ?>
    <div class="property">
        <dt><?php echo $translate('Item sets'); ?></dt>
        <div class="values">
            <?php foreach ($itemSets as $itemSet): ?>
            <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></dd>
            <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
    </dl>
    <?php $relatedItemValues = $item->value('dcterms:relation',['all' => true]); ?>
    <?php if ($relatedItemValues): ?>
        <h3>Related Items</h3>
        <?php $numRelatedItems = count($relatedItemValues); ?>
        <?php $i = 0; ?>
        <?php foreach ($relatedItemValues as $relatedItemValue): ?>
            <?php $relatedItem =  $relatedItemValue->valueResource(); ?>
            <?php echo $relatedItem->linkRaw($this->thumbnail($relatedItem, 'square')); ?>
            <?php if(++$i !== $numRelatedItems): ?>
                <hr>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    
    <?php $this->trigger('view.show.after'); ?>
</div>